### ISSUE TITLE
Attack-Windows password

### ISSUE THREAD

**Issue by yutianqaq** [WesleyWong420/RedTeamOps-Havoc-101#2]
I downloaded Attacker Windows-No-TPM.zip and Attacker Windows.zip both require a password.
<img width="353" alt="Snipaste_2023-07-24_19-24-35" src="https://github.com/WesleyWong420/RedTeamOps-Havoc-101/assets/40353095/0831e649-3527-4bdb-bb3f-6675fcd48492">

**Comment by WesleyWong420** [comment]
The password was applied unintentionally by the TPM module, so I have no idea what the password is. The only solution to bypass it is by removing the TPM configuration from the .vmx file. (Open it with notepad and remove TPM lines)
